apiVersion: apps/v1
kind: Deployment
metadata:
  name: max-object-detector
  labels:
    app: max-object-detector
spec:
  selector:
    matchLabels:
      app: max-object-detector
  replicas: 5
  template:
    metadata:
      labels:
        app: max-object-detector
    spec:
      topologySpreadConstraints:
      - maxSkew: 5
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: max-object-detector
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - max-object-detector
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: max-object-detector
        image: quay.io/codait/max-object-detector:latest
        ports:
        - containerPort: 5000
        env:
        - name: DISABLE_WEB_APP
          value: "false"
